# Stubs for uttut.toolkits.get_kth_combination (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def get_kth_combination(*args, **kwargs) -> Any: ...
